name: Deploy to Hugging Face Space

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # <-- FULL history, not shallow
          lfs: false       # we aren't using LFS; skip

      - name: Ensure full clone (unshallow)
        run: |
          if git rev-parse --is-shallow-repository | grep -q true; then
            git fetch --unshallow
          fi

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Mirror to Hugging Face Space
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_TOKEN:    ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}   # e.g. summer-want-sushi/healthtrack-agent
          HF_SPACE_BRANCH: main
        run: |
          set -euo pipefail

          REMOTE_URL="https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE_ID}"

          if git remote | grep -q '^hf$'; then
            git remote set-url hf "$REMOTE_URL"
          else
            git remote add hf "$REMOTE_URL"
          fi

          # Push HEAD to the Space branch, force to keep them in sync
          git push hf "HEAD:${HF_SPACE_BRANCH}" --force
